metadata:
  name: erlang-shackle
  description: "High-Performance Erlang Network Client Framework which provides the following features:
  Backpressure via backlog (OOM protection)
  Fast pool implementation (random, round_robin)
  Managed timeouts
  Multi-protocol support (SSL / TCP / UDP)
  Performance-optimized
  Request pipelining
  Smart reconnect mechanism (exponential backoff)"
  labels:
    jira-project: DEGA
    jira-board: 189
  links:
    - url: https://github.com/adgear/erlang-shackle/blob/master/README.md
      title: Component Documentation Page
spec:
  owner: cg-dsp-bidding-system
  type: library
  lifecycle:  production
